[package]
name = "rathena-web-editor"
version = "1.0.0"
description = "rAthena Database Editor — Desktop Edition (Tauri v2)"
authors = ["Taig4o"]
edition = "2021"

[lib]
name = "rathena_web_editor_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
